language: android
jdk: oraclejdk7
before_install: git submodule update --init

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.2
    - android-19
